### ISSUE TITLE
HomeLede2021.06.13 版本SoftPkgs中无TG3驱动

### ISSUE THREAD

**Issue by double2w** [xiaoqingfengATGH/HomeLede#109]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：HomeLede2021.06.13 版本SoftPkgs中无TG3驱动

### (2) 路由器型号和固件版本

A：HomeLede2021.06.13

### (3) 详细日志

A：

**Comment by xiaoqingfengATGH** [comment]
驱动不会在软件包中提供，请直接编译源码
