### ISSUE TITLE
Passwall中无法使用防火墙表

### ISSUE THREAD

**Issue by thinkjam** [xiaoqingfengATGH/HomeLede#118]
使用最新的HomeLede v2021.06.13 based on OpenWrt R21.6.1 / LuCI Master (git-21.124.16145-8385092)版本
安装后启用Passwall，选择模式为防火墙表，无法访问国外网站，调整为中国列表以外可以解决，但这样很多正常访问的外网岂不是耗用了流量？还请各位遇到类似问题的朋友帮忙解决，谢谢！

**Comment by SakuraFallingMad** [comment]
尝试dns模式不用homelede特供分流解析，看看情况
再不行，自定义gfwlist更新地址：https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/greatfire.txt

**Comment by xiaoqingfengATGH** [comment]
2022.05.04及以后版本，支持PSW全模式。
