### ISSUE TITLE
chinadns-ng解析域名问题

### ISSUE THREAD

**Issue by ajdgsu** [xiaoqingfengATGH/HomeLede#119]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x ] 没有类似的issue

### (1) 具体问题

最近在使用我自己搭建的grpc服务器时，发现使用国外的dns延迟比国内还低。但是这也就导致chinadns-ng一直在使用可信dns去请求域名(也就是使用国外dns)，这也就导致很多软件(像steam)一直走国外，怎么改也回不来；我知道可以使用edns但是使用之后一些域名会被解析到被墙的ip，亦或者解析到香港日本那里导致我节点速度奇慢无比(我的节点在美国)

所以说能否给chinadns-ng添加一个强制使用竞争模式的功能，无论可信dns速度多快都使用国内dns去解析国内域名而不是使用可信dns去解析国内域名

### (2) 路由器型号和固件版本

A： git-21.205.18243-ef71a33)

**Comment by xiaoqingfengATGH** [comment]
情况描述非常准确。

chinadns-ng确实有强制公平模式的说法，可以再启动初始化脚本中，直接加上公平模式参数。

开启公平模式后，会强制等待两类DNS返回，应该可以很好解决你的问题。
