### ISSUE TITLE
外网使用homeconnect链接，国内正常，国外无法访问

### ISSUE THREAD

**Issue by charlotte-ben** [xiaoqingfengATGH/HomeLede#120]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题
使用华硕路由器作为主路由，homelede作为旁路,DHCP在主路由
1.开启openclash上网，开启自定义上游DNS服务器
2.开启homeconnect
使用默认配置

内网机器修改网关和dns为homelede地址，国内国外访问正常
内网中使用homeconnect链接，国内国外访问正常

外网使用homeconnect链接，国内正常，**国外无法访问**

### (2) 路由器型号和固件版本

1.路由器为pve虚拟机
2.固件版本HomeLede v2021.06.13

**Comment by charlotte-ben** [comment]
除了接口位置修改静态ip，网关和dns为主路由的ip，桥接网卡没有改
其他的位置全部都是默认配置

**Comment by SakuraFallingMad** [comment]
dns设为homelede的，一种情况你使用homeconnect链接，你查看下收到推送的dns地址是homelede的吗，可能是主路由ip，所以可能被污染了

**Comment by charlotte-ben** [comment]
> dns设为homelede的，一种情况你使用homeconnect链接，你查看下收到推送的dns地址是homelede的吗，可能是主路由ip，所以可能被污染了

多谢回答，目前我没有使用homeconnect了
