### ISSUE TITLE
最新版本 编译到 subconverter 错误 尝试了多次

### ISSUE THREAD

**Issue by yer2018** [xiaoqingfengATGH/HomeLede#125]
-- The CXX compiler identification is GNU 8.4.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /home/test/HomeLede/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/bin/x86_64-openwrt-linux-musl-g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test HAVE_TO_STRING
-- Performing Test HAVE_TO_STRING - Failed
-- Found PkgConfig: /home/test/HomeLede/staging_dir/host/bin/pkg-config (found version "1.7.3")
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Checking for module 'libevent>=2.1.10'
--   Found libevent, version 2.1.12
CMake Error at /home/test/HomeLede/staging_dir/host/share/cmake-3.19/Modules/FindCURL.cmake:165 (message):
  CURL: Required feature IMPORTED_TARGET is not found
Call Stack (most recent call first):
  CMakeLists.txt:69 (FIND_PACKAGE)

-- Configuring incomplete, errors occurred!
See also "/home/test/HomeLede/build_dir/target-x86_64_musl/subconverter-0.6.1-9f67b90/CMakeFiles/CMakeOutput.log".
See also "/home/test/HomeLede/build_dir/target-x86_64_musl/subconverter-0.6.1-9f67b90/CMakeFiles/CMakeError.log".
make[3]: *** [Makefile:62: /home/test/HomeLede/build_dir/target-x86_64_musl/subconverter-0.6.1-9f67b90/.configured_68b329da9893e34099c7d8ad5cb9c940] Error 1
make[3]: Leaving directory '/home/test/HomeLede/feeds/xiaoqingfeng/subconverter'
time: package/feeds/xiaoqingfeng/subconverter/compile#2.18#0.94#8.29
    ERROR: package/feeds/xiaoqingfeng/subconverter failed to build.

**Comment by windy-xu** [comment]
我也遇到同样的问题喽，请问您那边是怎么解决的啊

**Comment by yer2018** [comment]
> 我也遇到了同样的问题，请问你在哪里是如何解决的啊
make dirclean 清空编译缓存 删掉.config 重新拉取 .config 确认在 make menuconfig 中 subconverter 是未选择的

**Comment by windy-xu** [comment]
> > 我也遇到了同样的问题，请问你在哪里是如何解决的啊
> > make dirclean 清空编译缓存 删掉.config 重新拉取 .config 确认在 make menuconfig 中 subconverter 是未选择的

明白了，错误那就不编译它。。
