### ISSUE TITLE
home connect 下级路由无法连接

### ISSUE THREAD

**Issue by bernylinville** [xiaoqingfengATGH/HomeLede#126]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ x ] 没有类似的issue

### (1) 具体问题

A：home connect 下级路由无法连接

### (2) 路由器型号和固件版本

A：HomeLede v2021.10.03

### (3) 问题描述
lede 做主路由，配置了静态路由，在内网可以正常访问下级路由
在外网连接 home connect 后，可正常打开主路由网段，但是下级路由无法打开，也不确定在哪能配置 home connect 的静态路由

**Comment by SakuraFallingMad** [comment]
一种情况，请home connect的配置用同级网关，第二种情况，用softethervpn的管理工具配置vpn推送路由

**Comment by chnxan** [comment]
我在使用Hyper-V虚拟一个HomeLede时，外网通过homeConnect 回来，主路由网段都打不开，只能访问homelede本身

**Comment by chnxan** [comment]
> 

已解决，hyper-v需要开启虚拟机lan网卡的mac地址欺骗
