### ISSUE TITLE
使用root/password无法登陆管理界面

### ISSUE THREAD

**Issue by CI2VO5IXZ7** [xiaoqingfengATGH/HomeLede#127]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [X] 没有类似的issue

### (1) 具体问题

A：更新到1003后，选择没有保存配置，选择了恢复之前的配置备份。使用root/password无法登陆管理界面，显示“无效的用户名和/或密码！请重试。”

**Comment by SakuraFallingMad** [comment]
不能恢复配置备份，这是上游大版本更新luci后不兼容造成的，请手动设置
