### ISSUE TITLE
京东服务无法正常使用

### ISSUE THREAD

**Issue by SOLOKEM** [xiaoqingfengATGH/HomeLede#128]
## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：京东签到服务不可用，扫码之后手机端提示请升级至最新版，始终无法成功扫码；并且无法更新京东签到服务脚本客户端，所有的更新源地址都试过了。上一个版本也是这个问题，上一个版本前几个月是好用的，后来前几个月突然不行了，所以我更新到了10.03的最新版，发现还是一样。

### (2) 路由器型号和固件版本

A：ESXi 7.0+HomeLede v2021.10.03 based on OpenWrt R21.10.1 / LuCI Master (git-21.275.60467-5ec9940) 

### (3) 详细日志

A：
2021-10-27 01:01:00 Wednesday

‼️京东商城-京豆发生错误
‼️名称: Error
‼️描述: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Cookie"]

‼️京东商城-超市发生错误
‼️名称: Error
‼️描述: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Cookie"]

‼️京东金融-钢镚发生错误
‼️名称: Error
‼️描述: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Cookie"]

‼️京东转盘-查询发生错误
‼️名称: Error
‼️描述: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Cookie"]

‼️京东商城-闪购发生错误
‼️名称: Error
‼️描述: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Cookie"]

‼️京东现金-红包发生错误
‼️名称: Error
‼️描述: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Cookie"]

‼️京东魔方-查询发生错误
‼️名称: Error
‼️描述: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Cookie"]

‼️京东商城-现金发生错误
‼️名称: Error
‼️描述: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Cookie"]

‼️京东商城-金贴发生错误
‼️名称: Error
‼️描述: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Cookie"]

‼️京东商城-摇摇发生错误
‼️名称: Error
‼️描述: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Cookie"]

‼️京东秒杀-查询发生错误
‼️名称: Error
‼️描述: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Cookie"]

‼️京东汽车-状态发生错误
‼️名称: Error
‼️描述: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Cookie"]

‼️京东金融-签肆发生错误
‼️名称: Error
‼️描述: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Cookie"]

‼️京东金贴-双签发生错误
‼️名称: Error
‼️描述: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Cookie"]

‼️京东商城-卡包发生错误
‼️名称: Error
‼️描述: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Cookie"]

‼️京东商城-内衣发生错误
‼️名称: Error
‼️描述: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Cookie"]

‼️京东商城-电竞发生错误
‼️名称: Error
‼️描述: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Cookie"]

‼️京东商城-箱包发生错误
‼️名称: Error
‼️描述: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Cookie"]

‼️京东商城-服饰发生错误
‼️名称: Error
‼️描述: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Cookie"]

‼️京东商城-校园发生错误
‼️名称: Error
‼️描述: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Cookie"]

‼️京东商城-健康发生错误
‼️名称: Error
‼️描述: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Cookie"]

‼️京东商城-鞋靴发生错误
‼️名称: Error
‼️描述: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Cookie"]

‼️京东商城-童装发生错误
‼️名称: Error
‼️描述: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Cookie"]

‼️京东商城-母婴发生错误
‼️名称: Error
‼️描述: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Cookie"]

‼️京东商城-数码发生错误
‼️名称: Error
‼️描述: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Cookie"]

‼️京东商城-女装发生错误
‼️名称: Error
‼️描述: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Cookie"]

‼️京东商城-图书发生错误
‼️名称: Error
‼️描述: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Cookie"]

‼️京东拍拍-二手发生错误
‼️名称: Error
‼️描述: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Cookie"]

‼️京东商城-菜场发生错误
‼️名称: Error
‼️描述: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Cookie"]

‼️京东商城-陪伴发生错误
‼️名称: Error
‼️描述: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Cookie"]

‼️京东商城-清洁发生错误
‼️名称: Error
‼️描述: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Cookie"]

‼️京东商城-个护发生错误
‼️名称: Error
‼️描述: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Cookie"]

‼️金融京豆-双签发生错误
‼️名称: Error
‼️描述: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Cookie"]

‼️账户钢镚-查询发生错误
‼️名称: Error
‼️描述: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Cookie"]

‼️账户红包-查询发生错误
‼️名称: Error
‼️描述: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Cookie"]

‼️账户京豆-查询发生错误
‼️名称: Error
‼️描述: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Cookie"]

‼️账户金贴-查询发生错误
‼️名称: Error
‼️描述: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Cookie"]

‼️账户现金-查询发生错误
‼️名称: Error
‼️描述: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Cookie"]

【签到号一】:  获取失败
【签到概览】:  错误38个
【账号总计】:  获取失败
【其他总计】:  获取失败

京东商城-京豆: 异常, 已输出日志 ‼️
京东商城-超市: 异常, 已输出日志 ‼️
京东金融-钢镚: 异常, 已输出日志 ‼️
京东转盘-查询: 异常, 已输出日志 ‼️
京东商城-闪购: 异常, 已输出日志 ‼️
京东现金-红包: 异常, 已输出日志 ‼️
京东魔方-查询: 异常, 已输出日志 ‼️
京东商城-现金: 异常, 已输出日志 ‼️
京东商城-金贴: 异常, 已输出日志 ‼️
京东商城-摇摇: 异常, 已输出日志 ‼️
京东秒杀-查询: 异常, 已输出日志 ‼️
京东汽车-状态: 异常, 已输出日志 ‼️
京东金融-签肆: 异常, 已输出日志 ‼️
京东金贴-双签: 异常, 已输出日志 ‼️
京东商城-卡包: 异常, 已输出日志 ‼️
京东商城-内衣: 异常, 已输出日志 ‼️
京东商城-电竞: 异常, 已输出日志 ‼️
京东商城-箱包: 异常, 已输出日志 ‼️
京东商城-服饰: 异常, 已输出日志 ‼️
京东商城-校园: 异常, 已输出日志 ‼️
京东商城-健康: 异常, 已输出日志 ‼️
京东商城-鞋靴: 异常, 已输出日志 ‼️
京东商城-童装: 异常, 已输出日志 ‼️
京东商城-母婴: 异常, 已输出日志 ‼️
京东商城-数码: 异常, 已输出日志 ‼️
京东商城-女装: 异常, 已输出日志 ‼️
京东商城-图书: 异常, 已输出日志 ‼️
京东拍拍-二手: 异常, 已输出日志 ‼️
京东商城-菜场: 异常, 已输出日志 ‼️
京东商城-陪伴: 异常, 已输出日志 ‼️
京东商城-清洁: 异常, 已输出日志 ‼️
京东商城-个护: 异常, 已输出日志 ‼️
金融京豆-双签: 异常, 已输出日志 ‼️
账户钢镚-查询: 异常, 已输出日志 ‼️
账户红包-查询: 异常, 已输出日志 ‼️
账户京豆-查询: 异常, 已输出日志 ‼️
账户金贴-查询: 异常, 已输出日志 ‼️
账户现金-查询: 异常, 已输出日志 ‼️

签到用时: 1.57 秒

**Comment by xiaoqingfengATGH** [comment]
签到插件原作者已经不再维护，现有部分签到API仍旧可以工作。

**Comment by SOLOKEM** [comment]
> 

嗯嗯，谢谢啦。
