### ISSUE TITLE
Clash订阅成功 还是上不了梯

### ISSUE THREAD

**Issue by LilithXing** [xiaoqingfengATGH/HomeLede#131]
CLosed

**Comment by xiaole51** [comment]
Clash 的问题还真不少. 
我的也是虚拟机+旁路由.
测试俩个版本:
HomeLede v2021.02.27 based on OpenWrt R21.2.1 / LuCI Master (git-21.037.51918-08b66fb)
HomeLede v2021.11.10 based on OpenWrt R21.11.11 / LuCI Master (git-21.305.50167-1150dbe)

ws传输协议的节点全部连不上, 裸奔的tcp协议可以.
同样的节点在passwell一切正常.

**Comment by xiaole51** [comment]
误杀了. 
仔细观察配置文件,转换出来的ws节点中缺少skip-cert-verify: true参数导致节点无法连接. 
手动添加此参数后可正常链接.
