### ISSUE TITLE
最新版本重启后passwall和openclash均无法连接海外地址

### ISSUE THREAD

**Issue by LuoXingchen935** [xiaoqingfengATGH/HomeLede#134]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

## 2. 详细叙述
环境为软路由esxi，使用homelede，关机homelede后重启，openclash可以启动，可以测试节点延迟，但是github和youtube测试始终是连接超时，且openclash页面四个IP地址测试均返回的是国内地址，在控制面板变更节点后也无效果，openclash页面下的【上传  下载 上传总量  下载总量  活动连接】五项的数值均为0，关闭openclash，开启passwall，无法自动设定dnsmasq的上游地址。国内连接测试没问题，国外连接测试无法访问，使用nslookup测试google和youtube均可以返回归属于谷歌的地址。
### (1) 具体问题

A：openclash和passwall重启后无法连接外网

### (2) 路由器型号和固件版本

A：HomeLede v2021.11.10 based on OpenWrt R21.11.11

### (3) 详细日志

A：

**Comment by xiaoqingfengATGH** [comment]
确认下DNS是否正常运行。可以参考wiki里DNS故障排查说明。

你的现象可能是海外DNS启动失败。
