### ISSUE TITLE
ADGuardHome 更改端口号之后不生效

### ISSUE THREAD

**Issue by peterxu2002** [xiaoqingfengATGH/HomeLede#135]
## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x ] 查找过还没有人提交这个类似的问题

### (1) 具体问题

A：启动最新的版本 HomeLede v2021.11.10 based on OpenWrt R21.11.11
B：启动ADguardhome服务
C：尝试修改默认的端口号3000到其他端口比如4000, 5000, 6000
D: 尝试保存设置并重启ADguardhome服务
E：检查ADguardhome服务可以通过原来默认的3000端口访问，但不能通过修改后的自定义端口访问到。

### (2) 路由器型号和固件版本

A：X86 主机通过Hyper-V的形式虚拟启动

### (3) 详细日志

A：

**Comment by yer2018** [comment]
页面设置确实有问题
可以手动操作 修改  /etc/AdGuardHome/AdGuardHome.yaml 第二行3000 
然后 /etc/init.d/AdGuardHome reload

**Comment by xiaoqingfengATGH** [comment]
固件DNS方案中，AdGuardHome作为所有DNS入口，因此对于绝大多数用户，直接更改端口（53）并没有意义，因此没有做支持。
你提到的是更改AdGuardHome管理界面的端口，可以按照一楼方法修改。
