### ISSUE TITLE
chinadns-ng问题 

### ISSUE THREAD

**Issue by yer2018** [xiaoqingfengATGH/HomeLede#136]
自动更新在计划任务中为 0 3 * * 6 /usr/bin/chinadns-ng_update.sh >>/tmp/chinadns-ng_update.log 2>&1
实际没有该文件 
只有 /usr/bin/chinadns-ng-update-list.sh
需要修改 /etc/init.d/chinadns-ng  中 chinadns-ng_update.sh 为 chinadns-ng-update-list.sh

还有生成备份时 没有备份 自定义 黑白名单  /etc/chinadns-ng/blacklist.txt 和 /etc/chinadns-ng/whitelist.txt

**Comment by xiaoqingfengATGH** [comment]
近期版本已经修正了。
