### ISSUE TITLE
代理表

### ISSUE THREAD

**Issue by kaingao** [xiaoqingfengATGH/HomeLede#137]
你的嵌套DNS只支持“中国列表外”的代理模式。使用防火墙表会各种出错。
问题是，各种游戏的启动程序，客户端等等，如EPIC等等对区域很敏感。直接中国最方便。但是你这个直接带出去了，各种问题。
还有有的软件甚至由于代理了，出现SSL错误。无法下载或者浏览等问题。

**Comment by xiaoqingfengATGH** [comment]
之前版本PSW只适配了中国列表以外模式，2022.05.04版本开始支持所有模式，可以体验。
