### ISSUE TITLE
更新固件，支持一下hysteria吧

### ISSUE THREAD

**Issue by ugvfpdcuwfnh** [xiaoqingfengATGH/HomeLede#138]
只是个建议哈，最近mjj全部在转用hysteria，都在暴力发包。

大家一起用hysteria一起卷，你不用，隔壁用了卷死你，不内卷都不行  o(╥﹏╥)o

**Comment by xiaoqingfengATGH** [comment]
固件中一直都有，最新版固件已经发布，可以直接体验。
