### ISSUE TITLE
希望v2022.05.05新增插件keepalived支持

### ISSUE THREAD

**Issue by RavenLiao** [xiaoqingfengATGH/HomeLede#139]
由于想做双机热备,所以需要该插件。上个版本还支持，这个版本的本地软件源就没有这个包了。
大佬能否帮忙编译一下，谢谢
这里是源码：https://github.com/openwrt/packages/tree/openwrt-22.03/net/keepalived

**Comment by xiaoqingfengATGH** [comment]
你可以先试试公共源里的包能否使用。

**Comment by RavenLiao** [comment]
还真可以,哈哈哈,主要一下子就用本地软件源了
顺便备份一下固件源:
src/gz openwrt_core https://mirrors.cloud.tencent.com/lede/snapshots/targets/x86/64/packages
src/gz openwrt_base https://mirrors.cloud.tencent.com/lede/snapshots/packages/x86_64/base
src/gz openwrt_homeclash https://mirrors.cloud.tencent.com/lede/snapshots/packages/x86_64/homeclash
src/gz openwrt_infinityfreedom https://mirrors.cloud.tencent.com/lede/snapshots/packages/x86_64/infinityfreedom
src/gz openwrt_lienol https://mirrors.cloud.tencent.com/lede/snapshots/packages/x86_64/lienol
src/gz openwrt_luci https://mirrors.cloud.tencent.com/lede/releases/18.06.9/packages/x86_64/luci
src/gz openwrt_packages https://mirrors.cloud.tencent.com/lede/snapshots/packages/x86_64/packages
src/gz openwrt_pw https://mirrors.cloud.tencent.com/lede/snapshots/packages/x86_64/pw
src/gz openwrt_routing https://mirrors.cloud.tencent.com/lede/snapshots/packages/x86_64/routing
src/gz openwrt_strongswanInDocker https://mirrors.cloud.tencent.com/lede/snapshots/packages/x86_64/strongswanInDocker
src/gz openwrt_telephony https://mirrors.cloud.tencent.com/lede/snapshots/packages/x86_64/telephony
src/gz openwrt_xiaoqingfeng https://mirrors.cloud.tencent.com/lede/snapshots/packages/x86_64/xiaoqingfeng
