### ISSUE TITLE
Passwall + ddns (aliyun)  识别错误ip

### ISSUE THREAD

**Issue by chnxan** [xiaoqingfengATGH/HomeLede#147]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ x] 没有类似的issue

## 2. 详细叙述
Passwall + ddns (aliyun) 侦测网址http://ipv4.ddnspod.com 有时候会把解析地址更新为Passwall那边的ip
### (1) 具体问题
Passwall + ddns (aliyun) 侦测网址http://ipv4.ddnspod.com 有时候会把解析地址更新为Passwall那边的ip
随后就会重新更正回来，我推测是分流有误，但应该如何排查呢
A：

### (2) 路由器型号和固件版本
2022-05-04
A：

### (3) 详细日志

A：

**Comment by xiaoqingfengATGH** [comment]
在passwall中，将上面网址加入白名单

**Comment by chnxan** [comment]
已解决
