### ISSUE TITLE
i need your help

### ISSUE THREAD

**Issue by z104866** [xiaoqingfengATGH/HomeLede#15]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [X ] 没有类似的issue

### (1) 具体问题

A：全程follow你的步骤 开了2台机器同时做编译 1台GCP的vps，1台家里的虚拟Ubuntu（全局上网）
但是还是出错，在helloworld 处

### (2) 路由器型号和固件版本

A：X86

### (3) 详细日志

A：helloworld

**Comment by xiaoqingfengATGH** [comment]
helloworld并未集成，，缺少的依赖可以去原作者repo里下载后，再一起编译。
