### ISSUE TITLE
如何修改home connect客户端ip段

### ISSUE THREAD

**Issue by grenceb** [xiaoqingfengATGH/HomeLede#154]
## 1.关于你要提交的问题
如何修改home connect客户端ip段？
Q：是否搜索了issue (使用 "x" 选择)
[ x] 没有类似的issue

## 2. 详细叙述
home connect设置vpn回家，但是home connect只能访问没有被墙的网站，使用爱快的下一跳网关可以解决这个问题，但是每次vpn连接的ip都是随机的，有办法修改home connect客户端ip段吗

**Comment by xiaoqingfengATGH** [comment]
目前实现是使用路由网桥dhcp来分配地址，可以参考这个思路来查找解决办法
