### ISSUE TITLE
DHCP分配的DNS一直都是192.168.1.1

### ISSUE THREAD

**Issue by wukebian** [xiaoqingfengATGH/HomeLede#156]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

## 2. 详细叙述
DHCP分配的DNS地址一直都是192.168.1.1
### (1) 具体问题

A：都是默认配置，只调整了lan口的网关，wan口改成PPPOE，路由器网有了，可以opkg update了，发现电脑无法上网，检查了之后发现DHCP分配的DNS是192.168.1.1，DHCP服务器是192.168.100.2，但是一直分配1.1，手动把电脑的DNS改成192.168.100.2之后就可以了，这显然不符合DHCP的功能

### (2) 路由器型号和固件版本

A：路由器X86（倍控N5105）
固件版本HomeLede v2023.02.05 based on OpenWrt R23.2.14 / LuCI Master (git-23.030.51978-89ccb85) 

### (3) 详细日志

A：不知道应该调取哪里的日志，如有必要提供日志请告知日志位置

**Comment by gulinghua** [comment]
DHCP 选项里加 6,192.168.100.2
