### ISSUE TITLE
WARNINGs about Makefile Dependencies

### ISSUE THREAD

**Issue by lacafjh** [xiaoqingfengATGH/HomeLede#159]
### 详细叙述

Warning that two dependent packages, `libjwt` and `sagernet-core` do not exist. 

警告 `libjwt` 和 `sagernet-core` 两个依赖包不存在。 

Both issues have been found in two other repositories. 

这两个问题在另外两个仓库中也已搜到。 

1. https://github.com/immortalwrt/packages/issues/1248 

2. https://github.com/kenzok8/openwrt-packages/issues/298 

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

VMware ESXi VM on Intel J4125
OS: LMDE 6.1.0-21-amd64

### 详细日志

```
WARNING: Makefile 'package/feeds/telephony/asterisk/Makefile' has a dependency on 'libjwt', which does not exist
WARNING: Makefile 'package/feeds/xiaoqingfeng/luci-app-ssr-plus/Makefile' has a dependency on 'sagernet-core', which does not exist
```

**Comment by xiaoqingfengATGH** [comment]
源码已经更新，ssr后续会处理，telephony错误已经消失。
