### ISSUE TITLE
无法上网

### ISSUE THREAD

**Issue by z104866** [xiaoqingfengATGH/HomeLede#16]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue
X
## 2. 详细叙述
终于编译成功，但是不能上网？
在路由器上用TTYD ping www.sina,com.cn 或者 ping114.114.114.114 都可以
但是用客户端DHCP 到的地址 192.168.1.x 只能ping 114.114.114.114 DNS无法解析任何地址
客户端 nslookup 显示 reqeust time out
### (1) 具体问题

A：

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：

**Comment by xiaoqingfengATGH** [comment]
请先确认wan配置正确，可以上网，再排查dhcp部分。
