### ISSUE TITLE
ImmortalWrt下Luci-app-homeconnect无法连接

### ISSUE THREAD

**Issue by aepub** [xiaoqingfengATGH/HomeLede#162]
### 详细叙述

homeconnect是我使用过的最简单的VPN，但是最近换了ImmortalWrt，内核版本 | 6.6.48，24.246，防火墙firewall貌似用的4，nftables。
将homeconnect源代码一起编译，把以前用的etc和usr文件放的files里面，新编译出来的固件，homeconnetc能够正常启动和创建用户（如果不把原来的etc和usr内相应文件放进去，编译出来的固件无法创建用户），但是以前能正常连接VPN的手机或者PC，对于ImmortalWrt都不能连接到vpn，提示：L2TP-VPN服务器未响应！是否是新的openwrt的防火墙对homeconnect端口没有开放？求解答！

### 重复 issue

- [X] 没有类似的 issue

### 具体型号

x86/64

### 详细日志

ImmortalWrt无法使用homeconnect

**Comment by LX1234567890123** [comment]
是啊我也是很想要这个功能 我的是homelede的22年版本 用这个VPN很多年了很方便 我也想把这个集成在更高版本的ImmortalWrt下
大佬这个问题有解决吗
