### ISSUE TITLE
关于DNS的问题

### ISSUE THREAD

**Issue by czxinshui** [xiaoqingfengATGH/HomeLede#17]
你好。有幸找到你的固件，看了你固件里面的说明，图文介绍很清晰。不过我对你里面的SmartDNS+ChinaDNS-NG有一点不太理解的地方，希望能指明，谢谢
在SmartDNS里面，默认端口是6053，你创建的服务组是mainland，第二端口是7053，你创建的服务组是overseas。
可是第二服务器默认是没开启的。在里面也没看到有任何命令是把他们归类然后开启的命令，请问第2端口真的有在工作吗？
因为在ChinaDNS-NG里面，我看到你把2个端口的地址都填在里面了，所以问一下

**Comment by xiaoqingfengATGH** [comment]
如果你仔细读过方案就会发现，海外组目前由dnscrypt-proxy接管，而不是smartdns。
另外，无法上网排查手册里，也有测试每组dns是否在工作的方法，可以自行参考验证。
