### ISSUE TITLE
编译的时候有选ChinaDNS-NG 没有显示出来。请问是怎么回事

### ISSUE THREAD

**Issue by czxinshui** [xiaoqingfengATGH/HomeLede#18]
编译的时候有选ChinaDNS-NG 没有显示出来。请问是怎么回事

**Comment by czxinshui** [comment]
编译的时候选 LuCI —> Applications —> luci-app-ChinaDNS-NG 编译出来还是没有显示ChinaDNS-NG求解

**Comment by xiaoqingfengATGH** [comment]
不会，固件每个版本都会带chinadns-ng，包含图形界面。

**Comment by czxinshui** [comment]
我用你的固件编译，真的没有显示chinadns-ng图形界面

**Comment by xiaoqingfengATGH** [comment]
我并没有遇到类似现象。请确认所有软件feed和源码是完全一致的。
