### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by kailsay** [xiaoqingfengATGH/HomeLede#19]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
没有类似的issue

## 2. 详细叙述
编译报错,每次都是这个错误，即使重新git也是到这一步就不行了，

### (2) 路由器型号和固件版本
X86

### (3) 详细日志

make[1]: *** [package/Makefile:107: /home/kailsay/homeLede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/kailsay/homeLede'
make: *** [/home/kailsay/homeLede/include/toplevel.mk:227: world] Error 2

**Comment by xiaoqingfengATGH** [comment]
你这里缺乏详细日志，无法判断问题，确认用了make -j1 V=s编译
