### ISSUE TITLE
希望解决一下升级问题

### ISSUE THREAD

**Issue by CORE2021** [xiaoqingfengATGH/HomeLede#21]
这个DNS方案很好，市面上完全找不到替代品，作者你这个是业余学的还是职业搞编程的呢，佩服佩服，表示也想学习
就是升级问题，不知道现在解决了吗，不能直接升级就导致这个固件只能适合虚拟机的玩家，没有照顾到实体机直接安装的人群

**Comment by xiaoqingfengATGH** [comment]
在线升级方式并不能适合于所有情况。在线升级实际就是直接分区替换，实际应用中，成功率并不高，往往会造成更多问题，导致路由出现奇怪现象。

对于替换固件，HomeLede的思路是：固件基本将复杂配置尽量简化，使得每次替换固件需要配置内容降低到较低水平。
目前每次更换固件，需要手动备份文件已经不多：
1 /etc/config/dhcp 静态地址分配
2 /etc/config/firewall 端口转发，端口开放
3 /etc/config/passwall 节点信息，机场不需要备份
4 /etc/config/ddns 动态域名配置
至于pppoe，多拨，手动设置一次就好，大概几分钟。

其他内容建议存储到局域网其他设备上。

升级这块，在解决问题计划中，但因为实用价值没那么高，因此优先级不高。有空会关注。

软路由面向的基本都是动手能力较强的人群，刷机是基本操作了，希望大家折腾愉快。
