### ISSUE TITLE
如何进行源码更新

### ISSUE THREAD

**Issue by xuanwumen** [xiaoqingfengATGH/HomeLede#22]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

### (1) 具体问题

A：作者你好，非常喜欢你的源码，但是如何执行源码更新，例如 git pull为什么更新不了

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：

**Comment by xiaoqingfengATGH** [comment]
代码编译是基础问题。建议熟悉下git操作。目前发出来的源码可以保证编译通过。
最简单做法，保留源码dl目录，其他全部删除，重新执行git pull。
