### ISSUE TITLE
0620的bug

### ISSUE THREAD

**Issue by bxworks** [xiaoqingfengATGH/HomeLede#23]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ x] 没有类似的issue

### (1) 具体问题

0620版本，
问题1：一刷完更改wan为pppoe 死活不拨号，必须删除wan从新创建，才会好，或者是 更改物理接口去别的接口。在改回eth1 才会拨号。
问题2：开了ad，smartdns，iphone的今日头条app一开始是可以访问的，过了几个小时，app内变成无法访问，网络错误，但是toutiao.com等网址打开均正常。安卓手机app也正常。
问题3：系统无法从web更新其他固件。

### (2) 路由器型号和固件版本

A：d2800 主机。双rtl8111千兆卡。

### (3) 详细日志

A：无。

**Comment by xiaoqingfengATGH** [comment]
使用、配置问题非软件缺陷。
