### ISSUE TITLE
发行软件源链接404

### ISSUE THREAD

**Issue by ChengZ996** [xiaoqingfengATGH/HomeLede#24]
`src/gz openwrt_core https://openwrt.proxy.ustclug.org/snapshots/targets/x86/64/packages
src/gz openwrt_base https://openwrt.proxy.ustclug.org/snapshots/packages/x86_64/base
src/gz openwrt_homeclash https://openwrt.proxy.ustclug.org/snapshots/packages/x86_64/homeclash
src/gz openwrt_lienol https://openwrt.proxy.ustclug.org/snapshots/packages/x86_64/lienol
src/gz openwrt_luci https://openwrt.proxy.ustclug.org/releases/18.06.8/packages/x86_64/luci
src/gz openwrt_packages https://openwrt.proxy.ustclug.org/snapshots/packages/x86_64/packages
src/gz openwrt_routing https://openwrt.proxy.ustclug.org/snapshots/packages/x86_64/routing
src/gz openwrt_strongswanInDocker https://openwrt.proxy.ustclug.org/snapshots/packages/x86_64/strongswanInDocker
src/gz openwrt_xiaoqingfeng https://openwrt.proxy.ustclug.org/snapshots/packages/x86_64/xiaoqingfeng`

以上源链接404

其中部分源链接可转化为` https://mirrors.bfsu.edu.cn/openwrt/snapshots`

**Comment by xiaoqingfengATGH** [comment]
以下官方源，国内有对应镜像。
src/gz openwrt_core https://openwrt.proxy.ustclug.org/snapshots/targets/x86/64/packages
src/gz openwrt_base https://openwrt.proxy.ustclug.org/snapshots/packages/x86_64/base
src/gz openwrt_luci https://openwrt.proxy.ustclug.org/releases/18.06.8/packages/x86_64/luci
src/gz openwrt_packages https://openwrt.proxy.ustclug.org/snapshots/packages/x86_64/packages
src/gz openwrt_routing https://openwrt.proxy.ustclug.org/snapshots/packages/x86_64/routing
其他源国内没有镜像。
没有镜像的源部分软件包已经随着固件附带的软件包发布，其他软件包如需要请使用源码自行编译。
