### ISSUE TITLE
反馈一下0627两个bug

### ISSUE THREAD

**Issue by KyonCN** [xiaoqingfengATGH/HomeLede#25]
反馈bug/问题模板，提建议请删除

### (1) 具体问题

A  1. upnp无法正常工作  
      2. ipsec vpn 很容易断 基本上连上一分钟就断掉了  macos和iPhone下都是这种情况  以前用的softether 提供的L2TP从没出现过类似情况

### (2) 路由器型号和固件版本

A：四网口软路由  双wan 动态IP接入  0627版本 

### (3) 详细日志

A：

**Comment by xiaoqingfengATGH** [comment]
1 请确认是以HomeLede作为主路由。旁路由，二级路由场景下，upnp应该在主路由开启才有意义。
   如果是主，确认试过了IGDv1模式开启及关闭。此版本，测试过迅雷X，BitComet及EMule均可以正常工作。

2 ipsec 在iPhone下，如果锁屏就会断开，这并不是ipsec server的问题。MAC下没有测试。
   Windows 10 下会长时间保持连接。

**Comment by KyonCN** [comment]
1 . 是作为主路由使用  IGDv1模式开启及关闭情况下都无效  测试了 qbittorrent和utorrent 
2. ipsec断流是在连上后 刷网页时发生  大概不到三分钟   我所在的内网不太稳定  不知道是不是内网丢包造成的
