### ISSUE TITLE
AdGuard Home日志文件过大的问题

### ISSUE THREAD

**Issue by yufeiyohi** [xiaoqingfengATGH/HomeLede#26]
固件版本：HomeLede v2020.06.20 based on OpenWrt R20.6.18 / LuCI Master (git-20.163.44275-dc93ce3)
运行AdGuard Home插件
日志配置及统计配置均勾选启用日志及保留时间为90天后
一周左右发现 文件querylog.json异常庞大，而此时AdGuard无法启用报无空间
文件位置： /usr/bin/AdGuardHome/data/querylog.json

请问如何扩充/usr目录大小，或修改querylog.json文件位置？

**Comment by xiaoqingfengATGH** [comment]
这是一个应用使用问题。基本思路，外挂硬盘，挂载到路由后，将你想重定位的路径映射到新挂载硬盘。
可以用软链接命令，ln -s，具体请搜索解决方案。
