### ISSUE TITLE
0718版本 dns解析有问题

### ISSUE THREAD

**Issue by KyonCN** [xiaoqingfengATGH/HomeLede#30]
开启passwall 白名单模式
部分国内网址ip无法解析 adguard home 显示servfail
国外网站一切正常
13:50:07
koolshare.cn
A
状态： SERVFAIL

未开启passwall时
国外未被墙网站打不开 apple.com github.com 等
在路由nslookup后发现 dns请求在54端口无响应  上游 smartdns 和chinadns-ng都能返回ip

应该是dnsmasq问题吧 我试着重启了几次 也一样

**Comment by xiaoqingfengATGH** [comment]
如果dnsmasq有问题，应该所有54端口dns请求都失败。

你是移动宽带吗？

**Comment by KyonCN** [comment]
> 如果dnsmasq有问题，应该所有54端口dns请求都失败。
> 
> 你是移动宽带吗？
我是电信

**Comment by xiaoqingfengATGH** [comment]
你是否开启了v6解析？试试关闭wan的“使用内置的ipv6管理”

**Comment by KyonCN** [comment]
我是完全禁用ipv6的 内网也没分配v6地址
我用GitHub actions 编译了最新的k5分支  目前使用没问题了
