### ISSUE TITLE
Aria2 无法启动

### ISSUE THREAD

**Issue by stingshen** [xiaoqingfengATGH/HomeLede#33]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ x] 没有类似的issue

### (1) 具体问题

A：HomeLede中的 Aria2 无法启动。Aria2 状态 一直显示为未运行。

### (2) 路由器型号和固件版本

A：X86 Proxmox VM HomeLede20200620

### (3) 详细日志

A：无日志输出。打开日志后日志文件夹也无日志

**Comment by xiaoqingfengATGH** [comment]
确认你已经设置好了下载目录（一个合法，存在的目录）后再启动。

**Comment by stingshen** [comment]
谢谢！问题解决。
