### ISSUE TITLE
使用IPSecVPN，阿里ddns，导入证书请教哪个对应哪个？

### ISSUE THREAD

**Issue by gzxiexl** [xiaoqingfengATGH/HomeLede#34]
大佬，本人ddns用的阿里的域名，下载的免费ssl有一年有效期，下载的apache证书有三个文件，跟您的教程里的有所不同。
三个文件如下：（我的域名以abc.com替代）
4063076_abc.com.key
4063076_abc.com_chain.crt
4063076_abc.com_public.crt
哪个导入到哪个请指导，谢谢

**Comment by xiaoqingfengATGH** [comment]
4063076_abc.com_public.crt - > server.crt
4063076_abc.com_chain.crt 改名 ca.crt
4063076_abc.com.key -> KEY
