### ISSUE TITLE
请问这种使用场景下DNS方案是否有效

### ISSUE THREAD

**Issue by stone10104** [xiaoqingfengATGH/HomeLede#39]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：我的家庭网络方案是，主路由华硕AX3000，homelede用作旁路由，旁路由网关指向主路由，主路由网关指向主路由自己，主路由开DHCP服务，旁路由关闭DHCP服务，对于局域网内有需求的设备，手动设置网关和DNS服务器为旁路由，请问这种情况下旁路由的DNS方案是否起作用？

### (2) 路由器型号和固件版本

A：

### (3) 详细日志

A：

**Comment by xiaoqingfengATGH** [comment]
看起来可以用。
