### ISSUE TITLE
路由界面去掉选中adguardhome后无法打开网页,必须勾选才能打开网页。

### ISSUE THREAD

**Issue by xiaolilir** [xiaoqingfengATGH/HomeLede#42]
### (1) 具体问题

A：路由界面去掉选中adguardhome后无法打开网页,必须勾选才能打开网页。

root@OpenWrt:/# nslookup www.baidu.com 127.0.0.1#6053
Server:         127.0.0.1
Address:        127.0.0.1#6053

Name:      www.baidu.com
www.baidu.com   canonical name = www.a.shifen.com
Name:      www.a.shifen.com
Address 1: 112.80.248.76
*** Can't find www.baidu.com: No answer

### (2) 路由器型号和固件版本

A：固件是最新的版本,9.5号的。

**Comment by xiaoqingfengATGH** [comment]
AdGuardHome是固件DNS方案中的主DNS，是整个局域网DNS解析入口，关闭后必然不能解析进而不能上网。

具体你可以读读固件wiki里关于dns的说明。

如果你有特殊需要，并且熟悉DNS相关软件的设置及原理可以自行调整。
