### ISSUE TITLE
私有软件服务源部分无法更新

### ISSUE THREAD

**Issue by xiaolilir** [xiaoqingfengATGH/HomeLede#43]
src/gz openwrt_base http://192.168.5.155:8989/homelede/base
src/gz openwrt_homeclash http://192.168.5.155:8989//homelede/homeclash
src/gz openwrt_lienol http://192.168.5.155:8989/homelede/lienol
src/gz openwrt_luci http://192.168.5.155:8989/homelede/luci
src/gz openwrt_packages http://192.168.5.155:8989/homelede/packages
src/gz openwrt_strongswanInDocker http://192.168.5.155:8989/homelede/strongswanInDocker
src/gz openwrt_xiaoqingfeng http://192.168.5.155:8989/homelede/xiaoqingfeng
src/gz openwrt_core http://192.168.5.155:8989/homelede/core
src/gz openwrt_infinityfreedom http://192.168.5.155:8989/homelede/infinityfreedom
src/gz openwrt_freifunk https://openwrt.proxy.ustclug.org/snapshots/packages/x86_64/freifunk
src/gz openwrt_routing https://openwrt.proxy.ustclug.org/snapshots/packages/x86_64/routing
src/gz openwrt_telephony https://openwrt.proxy.ustclug.org/snapshots/packages/x86_64/telephony

后面几个都不行

**Comment by xiaoqingfengATGH** [comment]
请忽略（删除）后面三个。
