### ISSUE TITLE
web中无法刷固件的问题

### ISSUE THREAD

**Issue by sekaiacg** [xiaoqingfengATGH/HomeLede#47]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ ] 没有类似的issue

## 2. 详细叙述
系统-备份/升级 选择gz压缩包更新时，无效

### (1) 具体问题

A：系统-备份/升级 选择gz压缩包更新时，无效

### (2) 路由器型号和固件版本

A：x86 软路由 9.12

### (3) 详细日志

A： /usr/libexec/validate_firmware_image：permission denied

解决办法：ssh登陆，chmod +x /usr/libexec/validate_firmware_image
git仓库中文件权限需要修正

**Comment by xiaoqingfengATGH** [comment]
感谢反馈，已经修正。
