### ISSUE TITLE
upnp失效的问题

### ISSUE THREAD

**Issue by pigrass** [xiaoqingfengATGH/HomeLede#55]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x ] 没有类似的issue

### (1) 具体问题

A：miniupnpd程序，开启后没有任何端口显示，经过搜索，修改/etc/config目录下upnpd文件，添加一行 option external_iface 'wan' 后，重启miniupnpd进程后，可以正常使用。希望下次更新固件时可以将这一条加入文件
![QQ截图20201001045630](https://user-images.githubusercontent.com/51767950/94738790-8243d180-03a2-11eb-9677-dc54200c0307.png)

### (2) 路由器型号和固件版本

A：20200905固件

### (3) 详细日志

A：

**Comment by xiaoqingfengATGH** [comment]
upnp会自动检测wan口，不少案例可以正常工作。

感谢分享经验，哪位如果遇到相似问题可以实践。
