### ISSUE TITLE
homeclash启动失败时恢复dnsmasq转发设置

### ISSUE THREAD

**Issue by sekaiacg** [xiaoqingfengATGH/HomeLede#59]
## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

## 2. 详细叙述
某些情况下homeclash启动失败，这时dnsmasq的转发设置并没有还原
### (1) 具体问题

A：某些情况下 openclash启动失败，这时dnsmasq的转发设置并没有还原

根据homeclash独有dns逻辑，临时修复方法：
start_fail方法添加几行
start_fail()
{
   kill_clash
   enable=$(uci get openclash.config.enable 2>/dev/null)
   dns_port=$(uci get openclash.config.dns_port 2>/dev/null)
   redirect_dns=$(uci get openclash.config.redirect_dns 2>/dev/null)
   masq_cache=$(uci get openclash.config.masq_cache 2>/dev/null)
   revert_dns "$redirect_dns" "$masq_cache" "$dns_port" "$enable"
   stop
   exit 0
}

**Comment by xiangfeidexiaohuo** [comment]
这个可以

**Comment by sekaiacg** [comment]
没有问题，暂时关闭
