### ISSUE TITLE
t群怎么没了

### ISSUE THREAD

**Issue by sekaiacg** [xiaoqingfengATGH/HomeLede#62]
rt

**Comment by CHNTDCS** [comment]
wiki的右侧列表最下面有链接的

**Comment by sekaiacg** [comment]
或者说，我被t了？？？？？

**Comment by sekaiacg** [comment]
是不是误ban了…

**Comment by xiaoqingfengATGH** [comment]
刚才打开了看下，还在。松了一口气。

KoolShare的帖子近期被删了，只能靠群联系大家了。

**Comment by sekaiacg** [comment]
> 刚才打开了看下，还在。松了一口气。
> 
> KoolShare的帖子近期被删了，只能靠群联系大家了。

t群我被踢了吗，加不了了，能不能查下

**Comment by sekaiacg** [comment]
> 刚才打开了看下，还在。松了一口气。
> 
> KoolShare的帖子近期被删了，只能靠群联系大家了。

为什么会显示 "sorry,this channel is not accessible." ？
该提示的中文意思是 "抱歉，该频道不可访问。"
若您使用不同的汉化包，可能会显示出相近意思的中文翻译。
出现这种情况，有两种可能：一是该频道已经解散，二就是频道管理员ban了你的账号。

**Comment by xiaoqingfengATGH** [comment]
你的telegram账号多少？看看能不能把你加进去？

**Comment by sekaiacg** [comment]
> 你的telegram账号多少？看看能不能把你加进去？

animeabc

**Comment by sekaiacg** [comment]
………
