### ISSUE TITLE
保留配置升级后，DHCP选项自动增加了1个DNS服务器

### ISSUE THREAD

**Issue by btdwv** [xiaoqingfengATGH/HomeLede#69]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：由于光猫的IP地址是192.168.1.1，我将软路由LAN的IP地址改成了192.168.50.1
      在web页面保留配置升级固件后，网络-接口-高级设置-DHCP选项会多出来"6,192.168.1.1"

### (2) 路由器型号和固件版本

A：从2020.09.05升级到2020.11.08、从2020.11.08升级到2020.12.01
      这2次升级都发生了这样的情况

### (3) 详细日志

A：
![捕获](https://user-images.githubusercontent.com/8338274/100893359-40482080-34f6-11eb-9db3-5f56a5c7bf21.PNG)
红框里是多出来的DNS服务器

**Comment by xiaoqingfengATGH** [comment]
多出来的那个是固件默认的公开DNS地址，删除即可。
