### ISSUE TITLE
关闭AdGuard后无法解析DNS

### ISSUE THREAD

**Issue by tooadstool** [xiaoqingfengATGH/HomeLede#70]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：AdGuard Home功能关闭后浏览器无法打开之前未访问过的网页，之前访问过的网页可以打开，疑似无法解析DNS

### (2) 路由器型号和固件版本

A：笔记本软路由+20201201_内核V5.4.79测试版

### (3) 详细日志

A：

**Comment by xiaoqingfengATGH** [comment]
AdGuardHome是默认DNS方案总入口，关闭必然导致DNS解析失败。

方案细节，请参考固件WIKI中DNS方案说明。

如果只是想禁用广告过滤，固件WIKI中包含AdGuardHome的操作说明。

建议细读固件WIKI。
