### ISSUE TITLE
已分配的 DHCPv6 租约问题

### ISSUE THREAD

**Issue by hgr-2000** [xiaoqingfengATGH/HomeLede#74]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x] 没有类似的issue

### (1) 具体问题

A：已分配的 DHCPv6 租约问题，里面有不知道什么设备的租约，名字xiaoqiang
### (2) 路由器型号和固件版本

A：2020.12.24特别版

### (3) 详细日志

A：
![xiaoqiang](https://user-images.githubusercontent.com/71929385/103458771-39573c80-4d46-11eb-9d11-88ecbe3439df.jpg)

**Comment by xiaoqingfengATGH** [comment]
能显示出来的就是接入你网络的设备。固件并没有内置任何租约。

**Comment by hgr-2000** [comment]
嗯，关闭了AP的DHCP，就没有了
