### ISSUE TITLE
Release Version Tag

### ISSUE THREAD

**Issue by g199209** [xiaoqingfengATGH/HomeLede#84]
请问目前最新的 Release 版本 `v2021.01.23 特别版 (内核：5.4.91)` 是基于哪个 commit 生成的？我看之前的 Release 都有 Tag 的，这个就没有了……

**Comment by xiaoqingfengATGH** [comment]
正式版本一定会有TAG，其他版本视情况打TAG。

可以根据Commit的日期，还原源码状态。
