### ISSUE TITLE
私有软件源服务器中pw目录不可访问.

### ISSUE THREAD

**Issue by xiaole51** [xiaoqingfengATGH/HomeLede#85]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [x ] 没有类似的issue

## 2. 详细叙述
建立私有软件服务器,pw目录不可访问.
### (1) 具体问题

A：

### (2) 路由器型号和固件版本
20210123 
其他版本未测试,估计也有同样问题.

### (3) 问题所在
httpd.conf 文件中遗漏pw配置,手动添加配置可解决.

<VirtualHost *>
...
Alias   /homelede/pw  "${SRVROOT}/../pw"
</VirtualHost>

<Directory "${SRVROOT}/../pw">
Options Indexes FollowSymLinks
AllowOverride None
Require all granted
</Directory>

**Comment by xiaoqingfengATGH** [comment]
感谢反馈，后续修正。
