### ISSUE TITLE
私有软件源PW目录无法访问或错误。

### ISSUE THREAD

**Issue by lovexinying** [xiaoqingfengATGH/HomeLede#95]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题
 * opkg_download: Failed to download http://192.168.1.181:5542/homelede/pw/Packages.gz, wget returned 8.
Q：是否搜索了issue (使用 "x" 选择)
* [  ] 没有类似的issue
x
## 2. 详细叙述
 * opkg_download: Failed to download http://192.168.1.181:5542/homelede/pw/Packages.gz, wget returned 8.
### (1) 具体问题
设置私有软件源后点击刷新列表出现如下错误
 * opkg_download: Failed to download http://192.168.1.181:5542/homelede/pw/Packages.gz, wget returned 8.
A：

### (2) 路由器型号和固件版本
CPUJ1900   版本20210214
A：

### (3) 详细日志
 * opkg_download: Failed to download http://192.168.1.181:5542/homelede/pw/Packages.gz, wget returned 8.
A：

**Comment by zhengcan** [comment]
推荐按此法安装私有软件源
https://github.com/xiaoqingfengATGH/HomeLede/issues/94
