### ISSUE TITLE
建议调整固件大小

### ISSUE THREAD

**Issue by 1261685372** [xiaoqingfengATGH/HomeLede#97]
新的测试版和特别版固件大小都被扩容至2.0gb
于是存在一个空间利用的问题
用2gb的盘写入固件空间不足
用4gb的盘写入固件又空闲了一大半的容量
因为空闲空间对普通人来说用处不大 所以建议作者调整一下固件大小以提升一下空间利用率

**Comment by KyonCN** [comment]
以前就是因为太小没法挂docker调大的 建议自己编译

**Comment by SevenPlusJun** [comment]
ext4的话可以自己划根目录大小，先用vmdk加载到虚拟机扩容后再进系统划分区扩根目录。

**Comment by SakuraFallingMad** [comment]
自行编译。2gb出厂标称容量是十进制，逻辑空间是二进制，自行修改需要的容量

**Comment by xiaoqingfengATGH** [comment]
可以参考下WIKI里，关于扩容的指导。
