### ISSUE TITLE
【BUG】passwall socks http 不分流

### ISSUE THREAD

**Issue by KyonCN** [xiaoqingfengATGH/HomeLede#98]
反馈bug/问题模板，提建议请删除

## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ x] 没有类似的issue

### (1) 具体问题

A：设备使用passwall提供的socks或http代理 不能分流 所有流量都会去国外服务器

### (2) 路由器型号和固件版本

A：目前在用0227 没记错的话应该一直有这个bug

**Comment by SakuraFallingMad** [comment]
这是feature，单开个socks走节点。。不是拿来分流的
需求这个，要去找xiaorouji

**Comment by KyonCN** [comment]
> 这是feature，单开个socks走节点。。不是拿来分流的
> 需求这个，要去找xiaorouji

好的 谢谢 目前找到分流方法了 就是开个xray服务端
